### ISSUE TITLE
실행파일에 인자 전달기능

### ISSUE THREAD

**Issue by alkee** [alkee/patcher#6]
`VersionInfo` 에 `ExecuteFilePath` 에 parameter 를 추가해 전달할 수 있는 기능.

보안문제 등은 추후에 필요한 경우 별도 issue 로 진행 가능할 것.

**Comment by alkee** [comment]
target(patch 되는 대상)은 이 parameter 를 이용해 patcher 에 의해 실행되었는지 확인할 수 있고, 필요한 경우 patcher 를 실행할 수 있을 것. 따라서 

 * target 에 의해 실행되는 경우(parent process?) 이 process 가 종료되기를 기다리는 작업 추가 필요.

**Comment by alkee-skia** [comment]
0500734 에서 기능 추가. version info `.json` 에 `Arguments` string 추가.

https://github.com/alkee/patcher/blob/0500734bfef82a21f33b77ee52b03f17c9a06592/Patcher/AppConfig.cs#L28
